version: "3"
services:
  server:
    build: ./src/server/
    ports:
     - "8080:8080"
    links:
     - worker
     - redis
    environment:
     - REDIS_URL=redis://randomkube-cache
  worker:
    build: ./src/worker/
    links:
      - redis
    environment:
      - REDIS_URL=redis://randomkube-cache
  redis:
    image: redis
    container_name: randomkube-cache
  lb:
    image: dockercloud/haproxy
    ports:
      - 3030:80
    links:
      - server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
